# Generated by Django 3.1 on 2020-08-18 11:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='LatLng',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Latitude')),
                ('lng', models.DecimalField(decimal_places=15, max_digits=17, verbose_name='Longitude')),
                ('address', models.CharField(max_length=50, verbose_name='Short Address')),
            ],
        ),
        migrations.CreateModel(
            name='area',
            fields=[
                ('latlng_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng')),
                ('radius', models.IntegerField(choices=[(100, '100 - Small'), (500, '500 - Medium'), (1000, '1000 - Important')])),
            ],
            bases=('app.latlng',),
        ),
        migrations.CreateModel(
            name='pin',
            fields=[
                ('latlng_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng')),
                ('kind', models.CharField(choices=[('food', 'Food'), ('construction', 'Construction'), ('ngo', 'Ngo headquarter'), ('danger', 'Sophomore'), ('red cross', 'Red Cross')], max_length=50)),
            ],
            bases=('app.latlng',),
        ),
    ]
