# Generated by Django 3.1 on 2020-08-18 23:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='damage',
            fields=[
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.pin')),
                ('level', models.CharField(choices=[('light', 'Light Damage'), ('moderate', 'Moderate Damage'), ('heavy', 'Heavy Damage')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='organization',
            fields=[
                ('pin', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='app.pin')),
                ('name', models.CharField(max_length=30)),
                ('description', models.TextField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
            ],
        ),
        migrations.AlterField(
            model_name='pin',
            name='kind',
            field=models.CharField(choices=[('food', 'Food'), ('construction', 'Construction'), ('ngo', 'Ngo headquarter'), ('danger', 'Danger'), ('red cross', 'Red Cross')], max_length=50),
        ),
    ]
