# Generated by Django 3.1 on 2020-08-21 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='damage',
            name='shortId',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='position',
            name='shortId',
            field=models.CharField(editable=False, max_length=6, primary_key=True, serialize=False),
        ),
    ]
