# Generated by Django 3.1 on 2020-08-21 13:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200821_1539'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='shortId',
        ),
        migrations.RemoveField(
            model_name='position',
            name='shortId',
        ),
        migrations.AlterField(
            model_name='damage',
            name='latlng_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng'),
        ),
        migrations.AlterField(
            model_name='position',
            name='latlng_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng'),
        ),
    ]
