# Generated by Django 3.1 on 2020-08-19 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20200819_0238'),
    ]

    operations = [
        migrations.CreateModel(
            name='position',
            fields=[
                ('latlng_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng')),
                ('name', models.CharField(max_length=30)),
                ('kind', models.CharField(choices=[('food', 'Food'), ('construction', 'Construction'), ('ngo', 'Ngo headquarter'), ('danger', 'Danger'), ('red cross', 'Red Cross')], max_length=50)),
                ('description', models.TextField(max_length=100)),
                ('contact', models.CharField(max_length=12)),
            ],
            bases=('app.latlng',),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lat',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name="Location's latitude"),
        ),
        migrations.AlterField(
            model_name='latlng',
            name='lng',
            field=models.DecimalField(decimal_places=15, max_digits=17, verbose_name="Location's Longitude"),
        ),
        migrations.DeleteModel(
            name='organization',
        ),
    ]
