# Generated by Django 3.1 on 2020-08-22 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200821_1645'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
