# Generated by Django 3.1 on 2020-08-19 01:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20200819_0427'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='damage',
            name='pin',
        ),
        migrations.AddField(
            model_name='damage',
            name='contact',
            field=models.CharField(default='', max_length=12),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damage',
            name='description',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='damage',
            name='latlng_ptr',
            field=models.OneToOneField(auto_created=True, default='', on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='app.latlng'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='damage',
            name='level',
            field=models.CharField(choices=[('light', 'Light Damage'), ('moderate', 'Moderate Damage'), ('heavy', 'Heavy Damage')], max_length=50, verbose_name="Damage's level"),
        ),
    ]
