# Generated by Django 3.1 on 2020-08-22 20:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_need_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='need',
            name='status',
        ),
    ]
