# Generated by Django 3.1 on 2020-08-22 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_remove_need_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='need',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
