# Generated by Django 3.1 on 2020-08-22 21:44

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_damage_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='position',
            name='time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
