# Generated by Django 3.1 on 2020-08-23 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0008_position_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='need',
            name='status',
            field=models.CharField(choices=[('Still in need', 'Still in need'), ('Need fulfilled', 'Need fulfilled')], default='Still in need', max_length=50),
        ),
    ]
